### ISSUE TITLE
Increase the height of the links

### ISSUE THREAD

**Issue by mohammadshaad** [MahekUnnisa/My-Social-Links#1]
Asslamualaikum!

I feel the height of the links rectangles can be increased. Also in mobile devices the width is a bit small, it can be increased.

If you don't mind, I would love to work on this issue and make the PR. Thank you

![image](https://user-images.githubusercontent.com/89409389/213878397-deb0a997-c75f-4e1f-927e-000f69d0c046.png)

![image](https://user-images.githubusercontent.com/89409389/213878514-665ea3bc-560f-4876-a69a-7cccd67efe32.png)

**Comment by MahekUnnisa** [comment]
Please do that. Also, add screenshots. Let's see. 
And in mobile, I actually created it that way on purpose.
Thanks!

**Comment by mohammadshaad** [comment]
Okay will look into it. Thank you
